from .variable_nmp import LearnedVariableNMP
#from .fixed_nmp import PhysicsNMP
#from .fixed_nmp import PhysicsStackNMP
#from .fixed_nmp import OnesNMP
#from .fixed_nmp import EyeNMP
#from .fixed_nmp import LearnedFixedNMP
from .fixed_nmp import FixedNMP
#from .fixed_nmp import PhysicsPlusLearnedNMP
from .stacked_nmp import StackedNMP
from .stacked_nmp import StackedFixedNMP
from .stacked_nmp import PhysicsStackedFixedNMP
